export { default as MLogin } from './login';
export { default as MRegister } from './register';
export { default as MVerification } from './verifikasi';
export { default as MHome } from './home';
export { default as MEsim } from './esim';
export { default as MListing } from './listing';
export { default as MFilter } from './filter';
export { default as MDetail } from './detail';
export { default as MStatus } from './status';
export { default as MHistory } from './history';
export { default as MProfile } from './profile';
export { default as MOrderDetail } from './orderDetail';
export { default as MCoupon } from './coupon';
export { default as MChangeNumber } from './changeNumber';
export { default as MEditProfile } from './editProfile';
export { default as MSupport } from './support';
export { default as MDetailProduct } from './detailProduct';
export { default as MCompatible} from './compatible';
export { default as MConfirm} from './confirm';
export { default as MActivate} from './activate';
